# .github/workflows/docker-image.yml
name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 4.1. Checkout
      - uses: actions/checkout@v4

      # 4.2. Сборка фронтенда (только если есть package.json)
      # - name: Install pnpm & build
      #   run: |
      #     npm install -g pnpm
      #     pnpm install
      #     pnpm run build

      # 4.3. Логин в GHCR
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: DiPorto
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4.4. Сборка и пуш Docker-образа
      - uses: docker/build-push-action@v5
        with:
          context: .   # корень репозитория, где лежит Dockerfile
          push: true
          tags: |
            ghcr.io/DiPorto/skills-publish-packages:latest
            ghcr.io/DiPorto/skills-publish-packages:sha-${{ github.sha }}
