# .github/workflows/docker-image.yml
name: Build and Publish Docker Image

permissions:
  contents: read      # чтение репо
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 4.1. Checkout
      - uses: actions/checkout@v4
     
      # 4.3. Логин в GHCR
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: diporto
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4.4. Сборка и пуш Docker-образа
      - uses: docker/build-push-action@v5
        with:
          context: .  # корень репозитория, где лежит Dockerfile
          push: true
          tags: |
            ghcr.io/diporto/skills-publish-packages:latest
            ghcr.io/diporto/skills-publish-packages:sha-${{ github.sha }}
