# .github/workflows/docker-image.yml
name: Enable GHCR & Build and Publish Docker Image

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  enable-ghcr-access:
    name: Enable GitHub Actions publishing to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Grant Actions access to Container package
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.request(
              'POST /orgs/{org}/packages/container/{package_name}/settings/add_actions_access',
              {
                org: 'diporto',
                package_name: 'skills-publish-packages'
              }
            );

  build-and-push:
    name: Build & Publish Docker Image
    runs-on: ubuntu-latest
    needs: enable-ghcr-access

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm & build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: diporto
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/diporto/skills-publish-packages:latest
            ghcr.io/diporto/skills-publish-packages:sha-${{ github.sha }}
